language: node_js
node_js:
- iojs
- 6
sudo: required
deploy:
  provider: heroku
  api_key:
    secure: lsIJIzuciFvwmj9AC3gPVEC5DI2pjgIdBXtRGbpjqBY9dyw5POKVdbyQ312lSBvQPB3+8JvfZllsV0qNgt7gyp3u3kcUkiuGeJ9TOoNf3oL7C4soi1N9k6lrKvaXJcygkbKn+U4stxJeTfUh83i8T1Q+Vwi8/4thZJsU9o/q2CowrbiommOWMKiTTxLyviaWxQnVcgA3ndeBSU7B2iKcH0ocEQK1cRa6oH7D/+I+SdMLc+8v2ViETg1dZXbRLKctfgcAZHUfwDxj/LaOxBUMmF2raFh3vTGaht/WLIngApsmjbhsbx3sDDWI/e9uBeACG2JLuUVYhcjC3ywjSJ8eqjLpXRdy83l6Q3CJVjuAnzjyylkrJCRHv6M7cSG6EjQgBA4TdrbYp/HYFIO/gNGhU2TRCktUNPZJo+SFsXBGBCGBUn9/wrSC0fbLbNWkaHdWG3hTWba3znCVuTPkfQdWTR/pF7nuaQRUszb+0Jjg1XNMdZpvjxHkFe45p+JFlJ6fnhgcOVX9+tIYS3/H8VddaYX4zVOX+KZ4WphxxFcfa01PeANMl9DKJkG3VhdNUbrNjrO88n68wxpys/eenb0IktLQ/hRArvE4Exhwsa26YqbEJRsMipKHOmCgHHTSYsxQj3qUO5SPT4Ig+rtClL+fgX7r456PJAOuui2axO1Ad7M=
